import { randomBytes } from "node:crypto";
import { existsSync } from "node:fs";
import {
  chmod,
  mkdir,
  readFile,
  readdir,
  rename,
  stat,
  unlink,
  writeFile,
} from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

import { ToolError } from "./errors.js";
import { ID_RE } from "./profiles.js";
import { makeDoneMarker } from "./pane.js";
import { MARKER_PREFIX } from "./paths.js";

/**
 * Boot-signal protocol (design 2026-07-08, codex/claude 리뷰 합의):
 * `pmux_agent_start` generates a `bootId`, launches the CLI with
 * `env PMUX_BOOT_FILE=~/.purplemux/boot/<bootId>` and wires a SessionStart
 * hook (this module's script) that writes that file. The orchestrator can
 * then tell "the CLI process came up and reached SessionStart" apart from
 * a launch failure — DIAGNOSTIC ONLY: boot-file existence never feeds
 * readiness classification (SessionStart fires before the composer/model
 * is usable, so treating it as ready would be a race).
 */

function purplemuxDir(): string {
  return join(homedir(), ".purplemux");
}

function bootDir(): string {
  return join(purplemuxDir(), "boot");
}

export function bootFilePath(bootId: string): string {
  if (!ID_RE.test(bootId)) {
    throw new ToolError(`Invalid bootId "${bootId}": must match ${ID_RE.source}.`);
  }
  return join(bootDir(), bootId);
}

const BOOT_HOOK_SCRIPT_PATH_BASENAME = "pmux-boot-hook.sh";

// The script derives everything from $PMUX_BOOT_FILE (set per-launch via an
// `env` prefix — `env` binary form so fish shells work too), so ONE static
// script serves every agent; no per-agent script generation. The path guard
// keeps a hostile/corrupt env var from writing outside ~/.purplemux/boot/.
// The trailing `|| true` / `exit 0`s keep a hook failure from ever breaking
// the CLI session itself.
const BOOT_HOOK_SCRIPT = `#!/bin/sh
# Generated by purplemux-mcp — do not edit. SessionStart boot signal:
# writes the file named by $PMUX_BOOT_FILE so the orchestrator can tell
# "CLI process reached SessionStart" apart from a launch failure.
set -u
[ -n "\${PMUX_BOOT_FILE:-}" ] || exit 0
case "$PMUX_BOOT_FILE" in
  "$HOME/.purplemux/boot/"*) ;;
  *) exit 0 ;;
esac
mkdir -p "\${PMUX_BOOT_FILE%/*}" 2>/dev/null || exit 0
printf 'ts=%s\\n' "$(date +%s)" > "$PMUX_BOOT_FILE" 2>/dev/null || true
exit 0
`;

/**
 * Idempotently write the boot hook script (0755). Rewrites when content
 * drifts (old generator version) so upgrades propagate. Returns the path.
 */
export async function ensureBootHookScript(): Promise<string> {
  const path = join(purplemuxDir(), BOOT_HOOK_SCRIPT_PATH_BASENAME);
  let current: string | undefined;
  try {
    current = await readFile(path, "utf8");
  } catch {
    current = undefined;
  }
  if (current !== BOOT_HOOK_SCRIPT) {
    await mkdir(purplemuxDir(), { recursive: true });
    // random tmp suffix: two concurrent first-starts must not race on one
    // tmp name and cost one of them its boot wiring (codex 리뷰 NIT).
    const tmp = `${path}.${randomBytes(4).toString("hex")}.tmp`;
    await writeFile(tmp, BOOT_HOOK_SCRIPT, { mode: 0o755 });
    await rename(tmp, path);
  }
  await chmod(path, 0o755);
  return path;
}

export type SettingsMerge = "merged" | "boot_only_missing" | "boot_only_parse_failed";

// Hook command strings cross TWO quoting layers: JSON/TOML first, then a
// shell when the CLI's hook runner executes them. Rather than guessing each
// runner's shell semantics and escaping for it, hook paths are ALLOWLISTED
// (same philosophy as MODEL_RE/ID_RE for the launch command — codex 리뷰
// [BLOCKING] 2026-07-08): only characters that are inert in double quotes
// for both sh and TOML. A homedir that fails this (quote, $, backtick,
// space, backslash…) degrades to bootWired:false instead of assembling a
// shell-expandable hook command.
const SAFE_HOOK_PATH_RE = /^[A-Za-z0-9/._-]+$/;

function assertSafeHookPath(path: string): void {
  if (!SAFE_HOOK_PATH_RE.test(path)) {
    throw new ToolError(
      `Hook path contains characters outside the safe allowlist: ${path}`,
    );
  }
}

interface HookEntry {
  matcher: string;
  hooks: Array<{ type: "command"; command: string; timeout?: number }>;
}

function bootHookEntry(hookScriptPath: string): HookEntry {
  assertSafeHookPath(hookScriptPath);
  // matcher:"" follows the purplemux app's own proven hooks.json pattern
  // for SessionStart (검증 항목: 실기동에서 fileSeen:true 확인).
  return {
    matcher: "",
    hooks: [
      { type: "command", command: `sh "${hookScriptPath}"`, timeout: 3 },
    ],
  };
}

/**
 * Build the per-launch claude settings file: a DEEP COPY of
 * ~/.purplemux/hooks.json (every top-level key preserved — statusLine etc.)
 * with the boot hook APPENDED to hooks.SessionStart (never replacing app
 * entries). Written to hooks-with-boot-<bootId>.json via tmp→rename so two
 * concurrent starts can never hand claude a torn JSON — per-bootId naming
 * (not a shared file) is what makes the concurrency safe (opus 리뷰 1(a)3).
 * A missing or unparseable hooks.json degrades to a boot-only settings file
 * and reports which via `settingsMerge` so the orchestrator can tell the
 * app hooks were dropped.
 */
export async function writeClaudeBootSettings(
  bootId: string,
  hookScriptPath: string,
): Promise<{ path: string; settingsMerge: SettingsMerge; appHooksWired: boolean }> {
  if (!ID_RE.test(bootId)) {
    throw new ToolError(`Invalid bootId "${bootId}": must match ${ID_RE.source}.`);
  }
  const appSettingsPath = join(purplemuxDir(), "hooks.json");
  let base: Record<string, unknown> = {};
  let settingsMerge: SettingsMerge = "boot_only_missing";
  try {
    const raw = await readFile(appSettingsPath, "utf8");
    try {
      const parsed = JSON.parse(raw) as unknown;
      if (parsed !== null && typeof parsed === "object" && !Array.isArray(parsed)) {
        base = parsed as Record<string, unknown>;
        settingsMerge = "merged";
      } else {
        settingsMerge = "boot_only_parse_failed";
      }
    } catch {
      settingsMerge = "boot_only_parse_failed";
    }
  } catch {
    settingsMerge = "boot_only_missing";
  }

  const merged = structuredClone(base);
  const hooks =
    merged.hooks !== null &&
    typeof merged.hooks === "object" &&
    !Array.isArray(merged.hooks)
      ? (merged.hooks as Record<string, unknown>)
      : {};
  merged.hooks = hooks;
  const sessionStart = Array.isArray(hooks.SessionStart)
    ? (hooks.SessionStart as unknown[])
    : [];
  hooks.SessionStart = [...sessionStart, bootHookEntry(hookScriptPath)];

  const path = join(purplemuxDir(), `hooks-with-boot-${bootId}.json`);
  const tmp = `${path}.tmp`;
  await mkdir(purplemuxDir(), { recursive: true });
  await writeFile(tmp, JSON.stringify(merged, null, 2));
  await rename(tmp, path);
  return { path, settingsMerge, appHooksWired: settingsMerge === "merged" };
}

/** Escape a value for embedding inside a TOML basic (double-quoted) string. */
export function tomlBasicStringEscape(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

const CODEX_HOOK_EVENTS = [
  "SessionStart",
  "UserPromptSubmit",
  "PreToolUse",
  "PostToolUse",
  "Stop",
  "PermissionRequest",
] as const;

function tomlHookConfig(event: string, commands: string[]): string {
  const hooks = commands
    .map((c) => `{type="command",command="${tomlBasicStringEscape(c)}"}`)
    .join(",");
  return `hooks.${event}=[{matcher=".*",hooks=[${hooks}]}]`;
}

/**
 * Raw `-c` config values wiring codex hooks. SessionStart carries the app
 * hook (when present) AND the boot hook IN ONE ARRAY — never two `-c`
 * flags for the same dotted key, which would be last-wins, not a merge
 * (codex 리뷰 합의). The boot hook is wired regardless of whether the app
 * hook script exists. Returns [] when there is nothing to wire.
 */
export function codexHookConfigs(o: {
  appHookPath?: string;
  bootHookPath?: string;
}): string[] {
  if (o.appHookPath !== undefined) assertSafeHookPath(o.appHookPath);
  if (o.bootHookPath !== undefined) assertSafeHookPath(o.bootHookPath);
  const configs: string[] = [];
  const sessionStart = [
    ...(o.appHookPath !== undefined ? [o.appHookPath] : []),
    ...(o.bootHookPath !== undefined ? [o.bootHookPath] : []),
  ];
  if (sessionStart.length > 0) {
    configs.push(tomlHookConfig("SessionStart", sessionStart));
  }
  if (o.appHookPath !== undefined) {
    for (const event of CODEX_HOOK_EVENTS) {
      if (event === "SessionStart") continue;
      configs.push(tomlHookConfig(event, [o.appHookPath]));
    }
  }
  return configs;
}

/**
 * Single-line bootstrap-echo prompt appended to the CLI command as a
 * positional initial prompt (auto-submit 실측 확인: codex v0.142.5, claude
 * v2.1.202, 2026-07-08). Uses the makeFileFooter split-string trick — the
 * complete `<<<PMUX_DONE …>>>` marker never appears as a contiguous
 * substring of the prompt (or therefore of the assembled command line), so
 * neither the composer echo nor tmux's command echo can be mistaken for
 * the real signal by parseDoneSignal. Single line ONLY: the command string
 * goes through the tab's shell, where an embedded newline would submit
 * early. The marker is generated with the fixed identity (agentId="boot",
 * turn=0, requestId=bootId) that wait_ready's expectEcho check uses.
 */
export const BOOTSTRAP_ECHO_AGENT_ID = "boot";
export const BOOTSTRAP_ECHO_TURN = 0;

export function buildBootstrapEchoPrompt(bootId: string): string {
  if (!ID_RE.test(bootId)) {
    throw new ToolError(`Invalid bootId "${bootId}": must match ${ID_RE.source}.`);
  }
  const doneRest = makeDoneMarker({
    agentId: BOOTSTRAP_ECHO_AGENT_ID,
    turn: BOOTSTRAP_ECHO_TURN,
    requestId: bootId,
    status: "complete",
  }).slice(MARKER_PREFIX.length);
  return (
    `연결 점검입니다. 어떤 도구도 사용하지 말고, ` +
    `"${MARKER_PREFIX}" 바로 뒤에 "${doneRest}" 를 이어붙인 한 줄만 정확히 출력하세요. ` +
    `다른 텍스트는 출력하지 마세요.`
  );
}

const PRUNE_AGE_MS = 24 * 60 * 60 * 1000;

// Filename patterns derived from the single ID allowlist (ID_RE) so an ID
// policy change cannot drift apart from the prune matchers. `.source` is
// anchored (^...$) — strip the anchors before composing.
const ID_SRC = ID_RE.source.slice(1, -1);
const BOOT_FILE_NAME_RE = new RegExp(`^${ID_SRC}(?:\\.tmp)?$`);
const BOOT_SETTINGS_NAME_RE = new RegExp(
  `^hooks-with-boot-${ID_SRC}\\.json(?:\\.tmp)?$`,
);

/**
 * Best-effort cleanup of boot artifacts older than 24h: boot-signal files
 * (except the current bootId) and per-launch hooks-with-boot-*.json
 * settings. Every fs error is swallowed — cleanup must never fail a start.
 */
export async function pruneBootArtifacts(currentBootId: string): Promise<void> {
  const cutoff = Date.now() - PRUNE_AGE_MS;
  const targets: Array<{ dir: string; match: (name: string) => boolean }> = [
    // Only names this module could have created (ID_RE + tmp variants) —
    // never arbitrary files someone else parked in the directory (codex
    // 리뷰 NIT).
    {
      dir: bootDir(),
      match: (name) =>
        name !== currentBootId &&
        BOOT_FILE_NAME_RE.test(name),
    },
    {
      dir: purplemuxDir(),
      match: (name) =>
        BOOT_SETTINGS_NAME_RE.test(name) &&
        !name.startsWith(`hooks-with-boot-${currentBootId}.json`),
    },
  ];
  for (const t of targets) {
    let names: string[];
    try {
      names = await readdir(t.dir);
    } catch {
      continue;
    }
    for (const name of names) {
      if (!t.match(name)) continue;
      const p = join(t.dir, name);
      try {
        const s = await stat(p);
        if (s.mtimeMs < cutoff) await unlink(p);
      } catch {
        // best-effort
      }
    }
  }
}

/** True when the boot-signal file for bootId exists (diagnostic only). */
export function bootFileSeen(bootId: string): boolean {
  return existsSync(bootFilePath(bootId));
}
